# start of generated code
  .data
  .align  2
  .globl  class_nameTab
  .globl  Main_protObj
  .globl  Int_protObj
  .globl  String_protObj
  .globl  bool_const0
  .globl  bool_const1
  .globl  _int_tag
  .globl  _bool_tag
  .globl  _string_tag
_int_tag:
  .word   10
_bool_tag:
  .word   11
_string_tag:
  .word   12
  .globl  _MemMgr_TEST
_MemMgr_TEST:
  .word   0
str_const75:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const1
  .byte  0
  .align  2
str_const74:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const2
  .ascii  "Main"
  .byte  0
  .align  2
str_const73:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const2
  .ascii  "Term"
  .byte  0
  .align  2
str_const72:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const3
  .ascii  "App"
  .byte  0
  .align  2
str_const71:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const4
  .ascii  "Lambda"
  .byte  0
  .align  2
str_const70:
  .word   12
  .word   7
  .word   String_dispTab
  .word   int_const5
  .ascii  "Variable"
  .byte  0
  .align  2
str_const69:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const2
  .ascii  "Expr"
  .byte  0
  .align  2
str_const68:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "LambdaListRef"
  .byte  0
  .align  2
str_const67:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const7
  .ascii  "LambdaListNE"
  .byte  0
  .align  2
str_const66:
  .word   12
  .word   7
  .word   String_dispTab
  .word   int_const8
  .ascii  "LambdaList"
  .byte  0
  .align  2
str_const65:
  .word   12
  .word   7
  .word   String_dispTab
  .word   int_const9
  .ascii  "VarListNE"
  .byte  0
  .align  2
str_const64:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const10
  .ascii  "VarList"
  .byte  0
  .align  2
str_const63:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const4
  .ascii  "String"
  .byte  0
  .align  2
str_const62:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const2
  .ascii  "Bool"
  .byte  0
  .align  2
str_const61:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const3
  .ascii  "Int"
  .byte  0
  .align  2
str_const60:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const11
  .ascii  "IO"
  .byte  0
  .align  2
str_const59:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const4
  .ascii  "Object"
  .byte  0
  .align  2
str_const58:
  .word   12
  .word   7
  .word   String_dispTab
  .word   int_const8
  .ascii  "_prim_slot"
  .byte  0
  .align  2
str_const57:
  .word   12
  .word   7
  .word   String_dispTab
  .word   int_const9
  .ascii  "SELF_TYPE"
  .byte  0
  .align  2
str_const56:
  .word   12
  .word   7
  .word   String_dispTab
  .word   int_const9
  .ascii  "_no_class"
  .byte  0
  .align  2
str_const55:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "<basic class>"
  .byte  0
  .align  2
str_const54:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const10
  .ascii  "\n};\n};\n"
  .byte  0
  .align  2
str_const53:
  .word   12
  .word   11
  .word   String_dispTab
  .word   int_const12
  .ascii  "  main() : EvalObject {\n"
  .byte  0
  .align  2
str_const52:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "class Main {\n"
  .byte  0
  .align  2
str_const51:
  .word   12
  .word   17
  .word   String_dispTab
  .word   int_const13
  .ascii  "(*Generated by lam.cl (Jeff Foster, March 2000)*)\n"
  .byte  0
  .align  2
str_const50:
  .word   12
  .word   16
  .word   String_dispTab
  .word   int_const14
  .ascii  "\n------------------cut here------------------\n"
  .byte  0
  .align  2
str_const49:
  .word   12
  .word   10
  .word   String_dispTab
  .word   int_const15
  .ascii  "Generating code for "
  .byte  0
  .align  2
str_const48:
  .word   12
  .word   20
  .word   String_dispTab
  .word   int_const16
  .ascii  "  apply(y : EvalObject) : EvalObject { { abort(); self; } };\n"
  .byte  0
  .align  2
str_const47:
  .word   12
  .word   19
  .word   String_dispTab
  .word   int_const17
  .ascii  "  init(p : Closure) : Closure {{ parent <- p; self; }};\n"
  .byte  0
  .align  2
str_const46:
  .word   12
  .word   12
  .word   String_dispTab
  .word   int_const18
  .ascii  "  get_x() : EvalObject { x };\n"
  .byte  0
  .align  2
str_const45:
  .word   12
  .word   14
  .word   String_dispTab
  .word   int_const19
  .ascii  "  get_parent() : Closure { parent };\n"
  .byte  0
  .align  2
str_const44:
  .word   12
  .word   9
  .word   String_dispTab
  .word   int_const20
  .ascii  "  x : EvalObject;\n"
  .byte  0
  .align  2
str_const43:
  .word   12
  .word   10
  .word   String_dispTab
  .word   int_const15
  .ascii  "  parent : Closure;\n"
  .byte  0
  .align  2
str_const42:
  .word   12
  .word   14
  .word   String_dispTab
  .word   int_const21
  .ascii  "class Closure inherits EvalObject {\n"
  .byte  0
  .align  2
str_const41:
  .word   12
  .word   16
  .word   String_dispTab
  .word   int_const14
  .ascii  "  eval() : EvalObject { { abort(); self; } };\n"
  .byte  0
  .align  2
str_const40:
  .word   12
  .word   12
  .word   String_dispTab
  .word   int_const22
  .ascii  "class EvalObject inherits IO {\n"
  .byte  0
  .align  2
str_const39:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const2
  .ascii  " =>\n"
  .byte  0
  .align  2
str_const38:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "beta-reduce: "
  .byte  0
  .align  2
str_const37:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .ascii  "z"
  .byte  0
  .align  2
str_const36:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .ascii  "y"
  .byte  0
  .align  2
str_const35:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .ascii  "x"
  .byte  0
  .align  2
str_const34:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const10
  .ascii  "  esac)"
  .byte  0
  .align  2
str_const33:
  .word   12
  .word   17
  .word   String_dispTab
  .word   int_const23
  .ascii  "    o : Object => { abort(); new EvalObject; };\n"
  .byte  0
  .align  2
str_const32:
  .word   12
  .word   12
  .word   String_dispTab
  .word   int_const22
  .ascii  "    c : Closure => c.apply(y);\n"
  .byte  0
  .align  2
str_const31:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const7
  .ascii  "  case x of\n"
  .byte  0
  .align  2
str_const30:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const2
  .ascii  " in\n"
  .byte  0
  .align  2
str_const29:
  .word   12
  .word   10
  .word   String_dispTab
  .word   int_const24
  .ascii  "     y : EvalObject <- "
  .byte  0
  .align  2
str_const28:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const11
  .ascii  ",\n"
  .byte  0
  .align  2
str_const27:
  .word   12
  .word   10
  .word   String_dispTab
  .word   int_const24
  .ascii  "(let x : EvalObject <- "
  .byte  0
  .align  2
str_const26:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const11
  .ascii  "))"
  .byte  0
  .align  2
str_const25:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const3
  .ascii  ")@("
  .byte  0
  .align  2
str_const24:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const11
  .ascii  "(("
  .byte  0
  .align  2
str_const23:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const3
  .ascii  "};\n"
  .byte  0
  .align  2
str_const22:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const25
  .ascii  ";}};\n"
  .byte  0
  .align  2
str_const21:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const26
  .ascii  "      x <- y;\n"
  .byte  0
  .align  2
str_const20:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const4
  .byte  92
  .ascii  "n\");\n"
  .byte  0
  .align  2
str_const19:
  .word   12
  .word   13
  .word   String_dispTab
  .word   int_const27
  .ascii  "    { out_string(\"Applying closure "
  .byte  0
  .align  2
str_const18:
  .word   12
  .word   14
  .word   String_dispTab
  .word   int_const28
  .ascii  "  apply(y : EvalObject) : EvalObject {\n"
  .byte  0
  .align  2
str_const17:
  .word   12
  .word   10
  .word   String_dispTab
  .word   int_const15
  .ascii  " inherits Closure {\n"
  .byte  0
  .align  2
str_const16:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "class Closure"
  .byte  0
  .align  2
str_const15:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const4
  .ascii  "self))"
  .byte  0
  .align  2
str_const14:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "new Closure))"
  .byte  0
  .align  2
str_const13:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const10
  .ascii  ").init("
  .byte  0
  .align  2
str_const12:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "((new Closure"
  .byte  0
  .align  2
str_const11:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .ascii  "."
  .byte  0
  .align  2
str_const10:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .byte  92
  .byte  0
  .align  2
str_const9:
  .word   12
  .word   6
  .word   String_dispTab
  .word   int_const10
  .ascii  "get_x()"
  .byte  0
  .align  2
str_const8:
  .word   12
  .word   11
  .word   String_dispTab
  .word   int_const29
  .ascii  "Error:  free occurrence of "
  .byte  0
  .align  2
str_const7:
  .word   12
  .word   8
  .word   String_dispTab
  .word   int_const6
  .ascii  "get_parent()."
  .byte  0
  .align  2
str_const6:
  .word   12
  .word   16
  .word   String_dispTab
  .word   int_const30
  .ascii  "\nError: Expr is pure virtual; can't gen_code\n"
  .byte  0
  .align  2
str_const5:
  .word   12
  .word   16
  .word   String_dispTab
  .word   int_const31
  .ascii  "\nError: Expr is pure virtual; can't substitute\n"
  .byte  0
  .align  2
str_const4:
  .word   12
  .word   17
  .word   String_dispTab
  .word   int_const23
  .ascii  "\nError: Expr is pure virtual; can't beta-reduce\n"
  .byte  0
  .align  2
str_const3:
  .word   12
  .word   16
  .word   String_dispTab
  .word   int_const31
  .ascii  "\nError: Expr is pure virtual; can't print self\n"
  .byte  0
  .align  2
str_const2:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .ascii  " "
  .byte  0
  .align  2
str_const1:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const0
  .ascii  "\n"
  .byte  0
  .align  2
str_const0:
  .word   12
  .word   9
  .word   String_dispTab
  .word   int_const32
  .ascii  "grading/lam-gc.cl"
  .byte  0
  .align  2
int_const32:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   17
int_const31:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   47
int_const30:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   45
int_const29:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   27
int_const28:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   39
int_const27:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   35
int_const26:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   14
int_const25:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   5
int_const24:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   23
int_const23:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   48
int_const22:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   31
int_const21:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   36
int_const20:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   18
int_const19:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   37
int_const18:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   30
int_const17:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   56
int_const16:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   61
int_const15:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   20
int_const14:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   46
int_const13:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   50
int_const12:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   24
int_const11:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   2
int_const10:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   7
int_const9:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   9
int_const8:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   10
int_const7:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   12
int_const6:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   13
int_const5:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   8
int_const4:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   6
int_const3:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   3
int_const2:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   4
int_const1:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   0
int_const0:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   1
bool_const0:
  .word   11
  .word   4
  .word   Bool_dispTab
  .word   0
bool_const1:
  .word   11
  .word   4
  .word   Bool_dispTab
  .word   1
class_nameTab:
  .word   str_const59
  .word   str_const60
  .word   str_const64
  .word   str_const65
  .word   str_const69
  .word   str_const70
  .word   str_const71
  .word   str_const72
  .word   str_const73
  .word   str_const74
  .word   str_const61
  .word   str_const62
  .word   str_const63
  .word   str_const66
  .word   str_const67
  .word   str_const68
class_objTab:
  .word   Object_protObj
  .word   Object_init
  .word   IO_protObj
  .word   IO_init
  .word   VarList_protObj
  .word   VarList_init
  .word   VarListNE_protObj
  .word   VarListNE_init
  .word   Expr_protObj
  .word   Expr_init
  .word   Variable_protObj
  .word   Variable_init
  .word   Lambda_protObj
  .word   Lambda_init
  .word   App_protObj
  .word   App_init
  .word   Term_protObj
  .word   Term_init
  .word   Main_protObj
  .word   Main_init
  .word   Int_protObj
  .word   Int_init
  .word   Bool_protObj
  .word   Bool_init
  .word   String_protObj
  .word   String_init
  .word   LambdaList_protObj
  .word   LambdaList_init
  .word   LambdaListNE_protObj
  .word   LambdaListNE_init
  .word   LambdaListRef_protObj
  .word   LambdaListRef_init
Object_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
IO_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
VarList_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   VarList.isNil
  .word   VarList.head
  .word   VarList.tail
  .word   VarList.add
  .word   VarList.print
VarListNE_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   VarListNE.isNil
  .word   VarListNE.head
  .word   VarListNE.tail
  .word   VarList.add
  .word   VarListNE.print
  .word   VarListNE.init
Expr_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   Expr.print_self
  .word   Expr.beta
  .word   Expr.substitute
  .word   Expr.gen_code
Variable_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   Variable.print_self
  .word   Variable.beta
  .word   Variable.substitute
  .word   Variable.gen_code
  .word   Variable.init
Lambda_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   Lambda.print_self
  .word   Lambda.beta
  .word   Lambda.substitute
  .word   Lambda.gen_code
  .word   Lambda.init
  .word   Lambda.apply
  .word   Lambda.gen_closure_code
App_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   App.print_self
  .word   App.beta
  .word   App.substitute
  .word   App.gen_code
  .word   App.init
Term_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   Term.var
  .word   Term.lam
  .word   Term.app
  .word   Term.i
  .word   Term.k
  .word   Term.s
Main_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   IO.out_string
  .word   IO.out_int
  .word   IO.in_string
  .word   IO.in_int
  .word   Term.var
  .word   Term.lam
  .word   Term.app
  .word   Term.i
  .word   Term.k
  .word   Term.s
  .word   Main.beta_reduce
  .word   Main.eval_class
  .word   Main.closure_class
  .word   Main.gen_code
  .word   Main.main
Int_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
Bool_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
String_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   String.length
  .word   String.concat
  .word   String.substr
LambdaList_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   LambdaList.isNil
  .word   LambdaList.headE
  .word   LambdaList.headC
  .word   LambdaList.headN
  .word   LambdaList.tail
  .word   LambdaList.add
LambdaListNE_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   LambdaListNE.isNil
  .word   LambdaListNE.headE
  .word   LambdaListNE.headC
  .word   LambdaListNE.headN
  .word   LambdaListNE.tail
  .word   LambdaList.add
  .word   LambdaListNE.init
LambdaListRef_dispTab:
  .word   Object.abort
  .word   Object.type_name
  .word   Object.copy
  .word   LambdaListRef.isNil
  .word   LambdaListRef.headE
  .word   LambdaListRef.headC
  .word   LambdaListRef.headN
  .word   LambdaListRef.reset
  .word   LambdaListRef.add
  .word   LambdaListRef.removeHead
  .word   -1
Object_protObj:
  .word   0
  .word   3
  .word   Object_dispTab
  .word   -1
IO_protObj:
  .word   1
  .word   3
  .word   IO_dispTab
  .word   -1
VarList_protObj:
  .word   2
  .word   3
  .word   VarList_dispTab
  .word   -1
VarListNE_protObj:
  .word   3
  .word   5
  .word   VarListNE_dispTab
  .word   0
  .word   0
  .word   -1
Expr_protObj:
  .word   4
  .word   3
  .word   Expr_dispTab
  .word   -1
Variable_protObj:
  .word   5
  .word   4
  .word   Variable_dispTab
  .word   str_const75
  .word   -1
Lambda_protObj:
  .word   6
  .word   5
  .word   Lambda_dispTab
  .word   0
  .word   0
  .word   -1
App_protObj:
  .word   7
  .word   5
  .word   App_dispTab
  .word   0
  .word   0
  .word   -1
Term_protObj:
  .word   8
  .word   3
  .word   Term_dispTab
  .word   -1
Main_protObj:
  .word   9
  .word   3
  .word   Main_dispTab
  .word   -1
Int_protObj:
  .word   10
  .word   4
  .word   Int_dispTab
  .word   0
  .word   -1
Bool_protObj:
  .word   11
  .word   4
  .word   Bool_dispTab
  .word   0
  .word   -1
String_protObj:
  .word   12
  .word   5
  .word   String_dispTab
  .word   int_const1
  .word   0
  .word   -1
LambdaList_protObj:
  .word   13
  .word   3
  .word   LambdaList_dispTab
  .word   -1
LambdaListNE_protObj:
  .word   14
  .word   7
  .word   LambdaListNE_dispTab
  .word   0
  .word   int_const1
  .word   0
  .word   0
  .word   -1
LambdaListRef_protObj:
  .word   15
  .word   5
  .word   LambdaListRef_dispTab
  .word   int_const1
  .word   0
  .globl  heap_start
heap_start:
  .word   0
  .text
  .globl  Main_init
  .globl  Int_init
  .globl  String_init
  .globl  Bool_init
  .globl  Main.main
Object_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
IO_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Object_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarList_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   IO_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarListNE_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   VarList_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Expr_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   IO_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Variable_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Expr_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Lambda_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Expr_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
App_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Expr_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Term_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   IO_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Main_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Term_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Int_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Object_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Bool_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Object_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
String_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Object_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Object_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListNE_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   LambdaList_init
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListRef_init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  jal   Object_init
  la    a0 int_const1
  sw    a0 12(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarList.isNil:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 bool_const1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarList.head:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label0
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label0:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  la    a0 Variable_protObj
  jal   Object.copy
  jal   Variable_init
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarList.tail:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label1
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label1:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  la    a0 VarList_protObj
  jal   Object.copy
  jal   VarList_init
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarList.add:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  sw    a0 0(sp)
  addi  sp sp -4
  la    a0 VarListNE_protObj
  jal   Object.copy
  jal   VarListNE_init
  bne   a0 x0 label2
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label2:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 16
  ret   
VarList.print:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label3
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label3:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarListNE.isNil:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 bool_const0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarListNE.head:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(s0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarListNE.tail:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
VarListNE.init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(tp)
  sw    a0 12(s0)
  lw    a0 12(tp)
  sw    a0 16(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
VarListNE.print:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(s0)
  bne   a0 x0 label4
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label4:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const2
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label5
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label5:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(s0)
  bne   a0 x0 label6
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label6:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Expr.print_self:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const3
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label7
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label7:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label8
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label8:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Expr.beta:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const4
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label9
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label9:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label10
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label10:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Expr.substitute:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const5
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label11
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label11:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label12
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label12:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Expr.gen_code:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const6
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label13
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label13:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label14
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label14:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Variable.init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(tp)
  sw    a0 12(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 16
  ret   
Variable.print_self:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label15
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label15:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Variable.beta:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Variable.substitute:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  lw    t1 4(sp)
  addi  sp sp 4
  mv    t2 a0
  la    a0 bool_const1
  beq   t1 t2 label16
  la    a1 bool_const0
  jal   equality_test
label16:
  lw    t1 12(a0)
  beqz  t1 label17
  lw    a0 12(tp)
  j     label18
label17:
  mv    a0 s0
label18:
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Variable.gen_code:
  addi  sp sp -16
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 20(tp)
  sw    a0 12(tp)
label19:
  lw    a0 12(tp)
  bne   a0 x0 label21
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label21:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  lw    t1 12(a0)
  beqz  t1 label22
  la    a0 bool_const0
  j     label23
label22:
  lw    a0 12(tp)
  bne   a0 x0 label26
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label26:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  lw    t1 4(sp)
  addi  sp sp 4
  mv    t2 a0
  la    a0 bool_const1
  beq   t1 t2 label25
  la    a1 bool_const0
  jal   equality_test
label25:
  lw    t1 12(a0)
  la    a0 bool_const1
  beqz  t1 label24
  la    a0 bool_const0
label24:
label23:
  lw    t1 12(a0)
  beq   t1 x0 label20
  la    a0 str_const7
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label27
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label27:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 12(tp)
  bne   a0 x0 label28
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label28:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 12(tp)
  j     label19
label20:
  mv    a0 x0
  lw    a0 12(tp)
  bne   a0 x0 label29
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label29:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  lw    t1 12(a0)
  beqz  t1 label30
  la    a0 str_const8
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label32
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label32:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label33
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label33:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label34
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label34:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label35
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label35:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  mv    a0 s0
  j     label31
label30:
  la    a0 str_const9
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label36
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label36:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
label31:
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
Lambda.init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(tp)
  sw    a0 12(s0)
  lw    a0 12(tp)
  sw    a0 16(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Lambda.print_self:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const10
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label37
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label37:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 12(s0)
  bne   a0 x0 label38
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label38:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const11
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label39
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label39:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(s0)
  bne   a0 x0 label40
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label40:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Lambda.beta:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Lambda.apply:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  bne   a0 x0 label41
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label41:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 16
  ret   
Lambda.substitute:
  addi  sp sp -20
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 24(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(s0)
  lw    t1 4(sp)
  addi  sp sp 4
  mv    t2 a0
  la    a0 bool_const1
  beq   t1 t2 label42
  la    a1 bool_const0
  jal   equality_test
label42:
  lw    t1 12(a0)
  beqz  t1 label43
  mv    a0 s0
  j     label44
label43:
  lw    a0 24(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  bne   a0 x0 label45
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label45:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 12(tp)
  la    a0 Lambda_protObj
  jal   Object.copy
  jal   Lambda_init
  sw    a0 16(tp)
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  bne   a0 x0 label46
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label46:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
label44:
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 28
  ret   
Lambda.gen_code:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const12
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label47
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label47:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  bne   a0 x0 label48
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label48:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label49
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label49:
  lw    t1 8(a0)
  lw    t1 16(t1)
  jalr  t1
  la    a0 str_const13
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label50
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label50:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(tp)
  bne   a0 x0 label51
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label51:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  lw    t1 12(a0)
  beqz  t1 label52
  la    a0 str_const14
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label54
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label54:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  j     label53
label52:
  la    a0 str_const15
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label55
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label55:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
label53:
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Lambda.gen_closure_code:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const16
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label56
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label56:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label57
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label57:
  lw    t1 8(a0)
  lw    t1 16(t1)
  jalr  t1
  la    a0 str_const17
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label58
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label58:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const18
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label59
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label59:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const19
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label60
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label60:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label61
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label61:
  lw    t1 8(a0)
  lw    t1 16(t1)
  jalr  t1
  la    a0 str_const20
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label62
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label62:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const21
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label63
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label63:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  bne   a0 x0 label64
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label64:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  bne   a0 x0 label65
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label65:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  la    a0 str_const22
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label66
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label66:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const23
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label67
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label67:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
App.init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(tp)
  sw    a0 12(s0)
  lw    a0 12(tp)
  sw    a0 16(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
App.print_self:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const24
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label68
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label68:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 12(s0)
  bne   a0 x0 label69
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label69:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const25
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label70
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label70:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(s0)
  bne   a0 x0 label71
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label71:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const26
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label72
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label72:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
App.beta:
  addi  sp sp -24
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(s0)
  bne   a0 x0 label74
  la    a0 str_const0
  li    t1 1
  jal   _case_abort2
label74:
  lw    t2 0(a0)
  li    t3 6
  blt   t2 t3 label75
  li    t3 6
  bgt   t2 t3 label75
  sw    a0 12(tp)
  lw    a0 16(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  bne   a0 x0 label77
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label77:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  j     label73
label75:
  li    t3 4
  blt   t2 t3 label76
  li    t3 7
  bgt   t2 t3 label76
  sw    a0 12(tp)
  lw    a0 12(s0)
  bne   a0 x0 label78
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label78:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 16(tp)
  la    a0 App_protObj
  jal   Object.copy
  jal   App_init
  sw    a0 20(tp)
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  bne   a0 x0 label79
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label79:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  j     label73
label76:
  jal   _case_abort
label73:
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
App.substitute:
  addi  sp sp -24
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 28(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 24(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(s0)
  bne   a0 x0 label80
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label80:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 12(tp)
  lw    a0 28(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 24(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  bne   a0 x0 label81
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label81:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 16(tp)
  la    a0 App_protObj
  jal   Object.copy
  jal   App_init
  sw    a0 20(tp)
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  bne   a0 x0 label82
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label82:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 32
  ret   
App.gen_code:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const27
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label83
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label83:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(s0)
  bne   a0 x0 label84
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label84:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  la    a0 str_const28
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label85
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label85:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const29
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label86
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label86:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  bne   a0 x0 label87
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label87:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  la    a0 str_const30
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label88
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label88:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const31
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label89
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label89:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const32
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label90
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label90:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const33
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label91
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label91:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const34
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label92
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label92:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Term.var:
  addi  sp sp -16
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 Variable_protObj
  jal   Object.copy
  jal   Variable_init
  sw    a0 12(tp)
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  bne   a0 x0 label93
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label93:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Term.lam:
  addi  sp sp -16
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 Lambda_protObj
  jal   Object.copy
  jal   Lambda_init
  sw    a0 12(tp)
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  bne   a0 x0 label94
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label94:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
Term.app:
  addi  sp sp -16
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 App_protObj
  jal   Object.copy
  jal   App_init
  sw    a0 12(tp)
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  bne   a0 x0 label95
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label95:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
Term.i:
  addi  sp sp -16
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const35
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label96
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label96:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 12(tp)
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label97
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label97:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 16
  ret   
Term.k:
  addi  sp sp -20
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const35
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label98
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label98:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 12(tp)
  la    a0 str_const36
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label99
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label99:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 16(tp)
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label100
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label100:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label101
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label101:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
Term.s:
  addi  sp sp -24
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const35
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label102
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label102:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 12(tp)
  la    a0 str_const36
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label103
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label103:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 16(tp)
  la    a0 str_const37
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label104
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label104:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 20(tp)
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label105
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label105:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label106
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label106:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label107
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label107:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label108
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label108:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label109
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label109:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label110
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label110:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
Main.beta_reduce:
  addi  sp sp -20
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const38
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label111
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label111:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 20(tp)
  bne   a0 x0 label112
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label112:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 bool_const0
  sw    a0 12(tp)
  mv    a0 x0
  sw    a0 16(tp)
label113:
  lw    a0 12(tp)
  lw    t1 12(a0)
  la    a0 bool_const1
  beqz  t1 label115
  la    a0 bool_const0
label115:
  lw    t1 12(a0)
  beq   t1 x0 label114
  lw    a0 20(tp)
  bne   a0 x0 label116
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label116:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 16(tp)
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  lw    t1 4(sp)
  addi  sp sp 4
  mv    t2 a0
  la    a0 bool_const1
  beq   t1 t2 label117
  la    a1 bool_const0
  jal   equality_test
label117:
  lw    t1 12(a0)
  beqz  t1 label118
  la    a0 bool_const1
  sw    a0 12(tp)
  j     label119
label118:
  lw    a0 16(tp)
  sw    a0 20(tp)
  la    a0 str_const39
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label120
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label120:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 20(tp)
  bne   a0 x0 label121
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label121:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
label119:
  j     label113
label114:
  mv    a0 x0
  la    a0 str_const1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label122
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label122:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 20(tp)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
Main.eval_class:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const40
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label123
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label123:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const41
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label124
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label124:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const23
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label125
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label125:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Main.closure_class:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 str_const42
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label126
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label126:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const43
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label127
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label127:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const44
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label128
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label128:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const45
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label129
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label129:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const46
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label130
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label130:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const47
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label131
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label131:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const48
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label132
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label132:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const23
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label133
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label133:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
Main.gen_code:
  addi  sp sp -28
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 LambdaListRef_protObj
  jal   Object.copy
  jal   LambdaListRef_init
  bne   a0 x0 label134
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label134:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 12(tp)
  la    a0 str_const49
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label135
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label135:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    a0 28(tp)
  bne   a0 x0 label136
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label136:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const50
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label137
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label137:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const51
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label138
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label138:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label139
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label139:
  lw    t1 8(a0)
  lw    t1 56(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label140
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label140:
  lw    t1 8(a0)
  lw    t1 60(t1)
  jalr  t1
  la    a0 str_const52
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label141
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label141:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 str_const53
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label142
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label142:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  la    a0 VarList_protObj
  jal   Object.copy
  jal   VarList_init
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 28(tp)
  bne   a0 x0 label143
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label143:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  la    a0 str_const54
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label144
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label144:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
label145:
  lw    a0 12(tp)
  bne   a0 x0 label148
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label148:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    t1 12(a0)
  la    a0 bool_const1
  beqz  t1 label147
  la    a0 bool_const0
label147:
  lw    t1 12(a0)
  beq   t1 x0 label146
  lw    a0 12(tp)
  bne   a0 x0 label149
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label149:
  lw    t1 8(a0)
  lw    t1 16(t1)
  jalr  t1
  sw    a0 16(tp)
  lw    a0 12(tp)
  bne   a0 x0 label150
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label150:
  lw    t1 8(a0)
  lw    t1 20(t1)
  jalr  t1
  sw    a0 20(tp)
  lw    a0 12(tp)
  bne   a0 x0 label151
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label151:
  lw    t1 8(a0)
  lw    t1 24(t1)
  jalr  t1
  sw    a0 24(tp)
  lw    a0 12(tp)
  bne   a0 x0 label152
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label152:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  lw    a0 24(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 20(tp)
  bne   a0 x0 label153
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label153:
  lw    t1 8(a0)
  lw    t1 52(t1)
  jalr  t1
  j     label145
label146:
  mv    a0 x0
  la    a0 str_const50
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label154
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label154:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 32
  ret   
Main.main:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label155
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label155:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  bne   a0 x0 label156
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label156:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label157
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label157:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label158
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label158:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  bne   a0 x0 label159
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label159:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label160
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label160:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label161
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label161:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  bne   a0 x0 label162
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label162:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  la    a0 str_const1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label163
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label163:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label164
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label164:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label165
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label165:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label166
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label166:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label167
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label167:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label168
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label168:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label169
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label169:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label170
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label170:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label171
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label171:
  lw    t1 8(a0)
  lw    t1 52(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label172
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label172:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label173
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label173:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label174
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label174:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label175
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label175:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label176
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label176:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label177
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label177:
  lw    t1 8(a0)
  lw    t1 52(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label178
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label178:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label179
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label179:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label180
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label180:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label181
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label181:
  lw    t1 8(a0)
  lw    t1 64(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label182
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label182:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label183
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label183:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label184
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label184:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label185
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label185:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label186
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label186:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label187
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label187:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label188
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label188:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label189
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label189:
  lw    t1 8(a0)
  lw    t1 64(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label190
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label190:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label191
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label191:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label192
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label192:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label193
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label193:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label194
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label194:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label195
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label195:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label196
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label196:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label197
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label197:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label198
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label198:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label199
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label199:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label200
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label200:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label201
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label201:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label202
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label202:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label203
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label203:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label204
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label204:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label205
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label205:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label206
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label206:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label207
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label207:
  lw    t1 8(a0)
  lw    t1 64(t1)
  jalr  t1
  mv    a0 s0
  bne   a0 x0 label208
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label208:
  lw    t1 8(a0)
  lw    t1 40(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label209
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label209:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label210
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label210:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label211
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label211:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label212
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label212:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label213
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label213:
  lw    t1 8(a0)
  lw    t1 44(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label214
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label214:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label215
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label215:
  lw    t1 8(a0)
  lw    t1 48(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label216
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label216:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label217
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label217:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label218
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label218:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  bne   a0 x0 label219
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label219:
  lw    t1 8(a0)
  lw    t1 64(t1)
  jalr  t1
  la    a0 int_const1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList.isNil:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 bool_const1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList.headE:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label220
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label220:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  la    a0 VarList_protObj
  jal   Object.copy
  jal   VarList_init
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList.headC:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label221
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label221:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  la    a0 Lambda_protObj
  jal   Object.copy
  jal   Lambda_init
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList.headN:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label222
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label222:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  la    a0 int_const1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList.tail:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  mv    a0 s0
  bne   a0 x0 label223
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label223:
  lw    t1 8(a0)
  lw    t1 0(t1)
  jalr  t1
  la    a0 LambdaList_protObj
  jal   Object.copy
  jal   LambdaList_init
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaList.add:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 20(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  mv    a0 s0
  sw    a0 0(sp)
  addi  sp sp -4
  la    a0 LambdaListNE_protObj
  jal   Object.copy
  jal   LambdaListNE_init
  bne   a0 x0 label224
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label224:
  lw    t1 8(a0)
  lw    t1 36(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 24
  ret   
LambdaListNE.isNil:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 bool_const0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListNE.headE:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 20(s0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListNE.headC:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 12(s0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListNE.headN:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListNE.tail:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 24(s0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListNE.init:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 24(tp)
  sw    a0 20(s0)
  lw    a0 20(tp)
  sw    a0 12(s0)
  lw    a0 16(tp)
  sw    a0 16(s0)
  lw    a0 12(tp)
  sw    a0 24(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 28
  ret   
LambdaListRef.isNil:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  bne   a0 x0 label225
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label225:
  lw    t1 8(a0)
  lw    t1 12(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListRef.headE:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  bne   a0 x0 label226
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label226:
  lw    t1 8(a0)
  lw    t1 16(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListRef.headC:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  bne   a0 x0 label227
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label227:
  lw    t1 8(a0)
  lw    t1 20(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListRef.headN:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  bne   a0 x0 label228
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label228:
  lw    t1 8(a0)
  lw    t1 24(t1)
  jalr  t1
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListRef.reset:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  la    a0 int_const1
  sw    a0 12(s0)
  la    a0 LambdaList_protObj
  jal   Object.copy
  jal   LambdaList_init
  sw    a0 16(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   
LambdaListRef.add:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(tp)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  lw    a0 16(s0)
  bne   a0 x0 label229
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label229:
  lw    t1 8(a0)
  lw    t1 32(t1)
  jalr  t1
  sw    a0 16(s0)
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  la    a0 int_const0
  jal   Object.copy
  lw    t2 12(a0)
  lw    t1 4(sp)
  addi  sp sp 4
  lw    t1 12(t1)
  add   t1 t1 t2
  sw    t1 12(a0)
  sw    a0 12(s0)
  lw    a0 12(s0)
  sw    a0 0(sp)
  addi  sp sp -4
  la    a0 int_const0
  jal   Object.copy
  lw    t2 12(a0)
  lw    t1 4(sp)
  addi  sp sp 4
  lw    t1 12(t1)
  sub   t1 t1 t2
  sw    t1 12(a0)
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 20
  ret   
LambdaListRef.removeHead:
  addi  sp sp -12
  sw    tp 12(sp)
  sw    s0 8(sp)
  sw    ra 4(sp)
  addi  tp sp 4
  mv    s0 a0
  lw    a0 16(s0)
  bne   a0 x0 label230
  la    a0 str_const0
  li    t1 1
  jal   _dispatch_abort
label230:
  lw    t1 8(a0)
  lw    t1 28(t1)
  jalr  t1
  sw    a0 16(s0)
  mv    a0 s0
  lw    tp 12(sp)
  lw    s0 8(sp)
  lw    ra 4(sp)
  addi  sp sp 12
  ret   

# end of generated code
